def build_report(inputs: dict, diagnostic: dict, executive_summary: str) -> str:
    recommendation = diagnostic["recommendation"]
    pain_lines = "\n".join(f"- {item}" for item in inputs["pain_points"]) or "- No pain points selected."
    opp_lines = "\n".join(f"- {item}" for item in diagnostic["opportunities"])
    roadmap_lines = "\n".join(f"- {item}" for item in diagnostic["roadmap_steps"])
    action_lines = "\n".join(f"- {item}" for item in diagnostic["actions"])
    return f"""# ClientOps Intake AI Diagnostic Report

## Executive Diagnostic Summary
{executive_summary}

## Business Profile
Business Name: {inputs['business_name'] or 'N/A'}
Business Type: {inputs['business_type']}
Team Size: {inputs['team_size']}
Revenue Stage: {inputs['revenue_stage']}
Tool Maturity: {inputs['tool_maturity']}
Urgency: {inputs['urgency']}

## Selected Pain Points
{pain_lines}

## Workflow Maturity
Score: {diagnostic['score']}%
Status: {diagnostic['label']}

## Primary Bottleneck
{diagnostic['primary_key'].title()}

## Recommended Toolkit App
{recommendation['app']}

Why: {recommendation['why']}

## Automation Opportunities
{opp_lines}

## 30-Day Improvement Roadmap
{roadmap_lines}

## Manager Action Plan
{action_lines}

## Current Process Notes
{inputs['current_process'] or 'Not provided.'}

## Desired Outcome
{inputs['desired_outcome'] or 'Not provided.'}

---
Generated by ClientOps Intake AI.
"""
